version: '3.6'

services:
  database:
    restart: always
    image: postgres:12 # use latest official postgres version
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5444:5432"

  gin_app:
    links:
      - database
    restart: always
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - database
    volumes:
      - ./backend:/go/src/projetoapi

  sockets:
    restart: always
    build: 
      context: ./socket-server/
      dockerfile: Dockerfile
    volumes:
      - './socket-server:/node_modules'
    ports:
      - "3000:3000"

  # frontend:
  # container_name: angular_service
  # build:
  #   context: ./frontend/
  #   dockerfile: Dockerfile
  # volumes:
  #   - './frontend:/usr/src/app/node_modules'
  # ports:
  #   - '4200:4200'
  # environment:
  #   - NODE_ENV=development
  #   - CHOKIDAR_USEPOLLING=true
  # depends_on: 
  #   - gin_app 
  # command: >
  #   bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --proxy-config proxy.config.js"
  
 

volumes:
  database-data: # named volumes can be managed easier using docker-compose


